### ISSUE TITLE
Exception Logged When Non-Existent App Id is Attempted

### ISSUE THREAD

**Issue by shamrice** [shamrice/discapp#270]
This is low priority as it doesn't effect the site's functionality.

When attempting to access the maintenance page of an app that does not exist, a NPE occurs trying to get the application. This should be updated to avoid the null pointer exception.

```
2020-04-22T05:35:05.888510+00:00 app[web.1]: 2020-04-22 05:35:05.888 ERROR 4 --- [io-13975-exec-8] i.g.s.d.s.a.ApplicationService           : No application found with appId: 10. Returning null.
2020-04-22T05:35:05.891474+00:00 app[web.1]: 2020-04-22 05:35:05.891 ERROR 4 --- [io-13975-exec-8] i.g.s.d.w.c.m.MaintenanceHomeController  : Error getting maintenance page for appId: 10 :: null
2020-04-22T05:35:05.891475+00:00 app[web.1]: 
2020-04-22T05:35:05.891476+00:00 app[web.1]: java.lang.NullPointerException: null
2020-04-22T05:35:05.891477+00:00 app[web.1]: at io.github.shamrice.discapp.web.controller.maintenance.MaintenanceController.setCommonModelAttributes(MaintenanceController.java:119) ~[classes!/:1.4.0]
2020-04-22T05:35:05.891478+00:00 app[web.1]: at io.github.shamrice.discapp.web.controller.maintenance.MaintenanceHomeController.getDiscMaintenanceView(MaintenanceHomeController.java:41) ~[classes!/:1.4.0]
2020-04-22T05:35:05.891479+00:00 app[web.1]: at sun.reflect.GeneratedMethodAccessor417.invoke(Unknown Source) ~[na:na]
2020-04-22T05:35:05.891479+00:00 app[web.1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242-heroku]
2020-04-22T05:35:05.891480+00:00 app[web.1]: at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242-heroku]
2020-04-22T05:35:05.891480+00:00 app[web.1]: at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891481+00:00 app[web.1]: at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891491+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891491+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891494+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891495+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891496+00:00 app[web.1]: at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891496+00:00 app[web.1]: at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891497+00:00 app[web.1]: at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891497+00:00 app[web.1]: at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891498+00:00 app[web.1]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-embed-core-9.0.21.jar!/:9.0.21]
2020-04-22T05:35:05.891498+00:00 app[web.1]: at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) [spring-webmvc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2020-04-22T05:35:05.891499+00:00 app[web.1]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.21.jar!/:9.0.21]
2020-04-22T05:35:05.891499+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.21.jar!/:9.0.21]
2020-04-22T05:35:05.891499+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.21.jar!/:9.0.21]
2020-04-22T05:35:05.891500+00:00 app[web.1]: at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.21.jar!/:9.0.21]
2020-04-22T05:35:05.891500+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.21.jar!/:9.0.21]
2020-04-22T05:35:05.891501+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.21.jar!/:9.0.21]
2020-04-22T05:35:05.891501+00:00 app[web.1]: at io.github.shamrice.discapp.web.filter.MaintenancePermissionFilter.doFilter(MaintenancePermissionFilter.java:115) [classes!/:1.4.0]
```

**Comment by shamrice** [comment]
Log actually comes from catch block in controller not unhandled exception. Very very very low priority ticket now if not completely not needed all together.

**Comment by shamrice** [comment]
This is only reproducible if the user is logged in as the root administrator account. If they are logged in as either a system account or user account, they will simply get the error message that they do not have permission to access the admin page for the non-existent disc app.

**Comment by shamrice** [comment]
Added check for NPE in ticket description. This is such an edge case that I don't feel like it's necessary to work on this issue any further for now.
