### ISSUE TITLE
Pulling CSS from the configuration cache sometimes causes timeouts

### ISSUE THREAD

**Issue by shamrice** [shamrice/discapp#471]
This has happened twice in the past couple of days. It seems that if two requests for CSS happen at the same exact time from two users, one user can be left hanging until the request times out.

It's possible it might be a bug with the new version of Spring Boot being used as well.

Logs:
```
26 Mar 2022 10:00:18.669211 <190>1 2022-03-26T14:00:18.264436+00:00 app web.1 - - 2022-03-26 14:00:18.264 ERROR 4 --- [o-6519-Acceptor] org.apache.tomcat.util.net.Acceptor : Socket accept failed
26 Mar 2022 10:00:18.66994 <190>1 2022-03-26T14:00:18.264445+00:00 app web.1 - -
26 Mar 2022 10:00:18.669275 <190>1 2022-03-26T14:00:18.264446+00:00 app web.1 - - java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
26 Mar 2022 10:00:18.669214 <190>1 2022-03-26T14:00:18.264446+00:00 app web.1 - - at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:548) ~[tomcat-embed-core-9.0.58.jar!/:na]
26 Mar 2022 10:00:18.669213 <190>1 2022-03-26T14:00:18.264446+00:00 app web.1 - - at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:78) ~[tomcat-embed-core-9.0.58.jar!/:na]
26 Mar 2022 10:00:18.669193 <190>1 2022-03-26T14:00:18.264447+00:00 app web.1 - - at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129) ~[tomcat-embed-core-9.0.58.jar!/:na]
26 Mar 2022 10:00:18.669154 <190>1 2022-03-26T14:00:18.264448+00:00 app web.1 - - at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

26 Mar 2022 10:00:24.063319 <158>1 2022-03-26T14:00:23.659749+00:00 heroku router - - at=info method=GET path="/indices/css/disc_39627.css" host=nediscapp.herokuapp.com request_id=a88c40c6-625f-41a1-a913-5711aa9cf4c9 fwd="71.56.235.155" dyno=web.1 connect=0ms service=6ms status=200 bytes=639 protocol=https

26 Mar 2022 10:00:48.786354 <158>1 2022-03-26T14:00:48.262116+00:00 heroku router - - at=error code=H12 desc="Request timeout" method=GET path="/indices/css/disc_39627.css" host=nediscapp.herokuapp.com request_id=528794bf-dd78-445f-b0b2-e03a6ef77beb fwd="71.56.235.155" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=httpsCritical
High Response Time

```

Same OS version as previous, just new spring boot version. Possibly related stackoverflow question: https://stackoverflow.com/questions/70937492/tomcat-ioexception-duplicate-accept-detected-this-is-a-known-os-bug-please-co

**Comment by shamrice** [comment]
Release 3.3.0 upgraded Spring Boot to 2.6.6. So far have not seen any more timeouts in the logs since 4/1. 
Will continue to monitor

**Comment by shamrice** [comment]
Still no timeouts since 4/1. Looks like that release may have fixed this issue. I'll continue to monitor and keep this ticket open until the 3.4.0 release or maybe at least one more month.
