### ISSUE TITLE
Failure to post new messges in some edge cases where a <pre> tag is used

### ISSUE THREAD

**Issue by shamrice** [shamrice/discapp#554]
The removal of auto generated ```<br />``` tags inside of a ```<pre>``` tag can, in some situations, cause the post to fail and the user get redirected back to the home page.

See article 40899 for an example. If posted with a pre-tag around the list, the message fails.

This causes the failure:
```
<pre>$
</pre>
```

Stack trace:
```
2022-10-05T15:32:34.007971+00:00 app[web.1]: 2022-10-05 15:32:34.007 ERROR 4 --- [o-12544-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Illegal group reference] with root cause
2022-10-05T15:32:34.007972+00:00 app[web.1]: 
2022-10-05T15:32:34.007973+00:00 app[web.1]: java.lang.IllegalArgumentException: Illegal group reference
2022-10-05T15:32:34.007973+00:00 app[web.1]: at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067) ~[na:na]
2022-10-05T15:32:34.007974+00:00 app[web.1]: at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997) ~[na:na]
2022-10-05T15:32:34.007975+00:00 app[web.1]: at io.github.shamrice.discapp.web.util.InputHelper.autogenerateNewLines(InputHelper.java:136) ~[classes!/:3.7.2]
2022-10-05T15:32:34.007975+00:00 app[web.1]: at io.github.shamrice.discapp.web.controller.application.DiscAppController.postNewThread(DiscAppController.java:779) ~[classes!/:3.7.2]
```

**Comment by shamrice** [comment]
This was an interesting bug to get fixed. Here's the comment I put in the code on how it was resolved:

This is a weird issue where matcher.appendReplacement expects a $ to reference a matching group number. So, if the text contains one that's not escaped, it blows up because it can't find the group. Interesting that appendReplacement has some extra 'magic' going on instead of just appending the text to the string builder and keeping track of the current position... anyway...

What's worse is that just escaping the $ with \$ doesn't always guarantee that it will work. The work around here is to replace it with the unicode char &#36, build the new text, and then at the end, change those &#36's back to $.

It could just be left at &#36, but I'm not sure how old web browsers would render the text at that point so to be safe, it's converted back.
